# This is a boilerplate parameters config generated for pipeline 'train'
# using Kedro 0.18.13.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.13/configuration/parameters.html

dataloaders:
  splits:
    train:
      frac: 0.7
      batch_size: 25
      shuffle: True
      n_examples_from_frac: 10
    valid:
      frac: 0.2
      batch_size: 25
      shuffle: False
      n_examples_from_frac: 10
    test:
      frac: 0.1
      batch_size: 25
      shuffle: False
      n_examples_from_frac: 10
  seed: 42

structure:
  num_layers: 10
  hidden_size: 64
  edge_dim: 2
  attn_size: 32
  attn_heads: 1
  aggr: mean

train:
  lr: 0.003
  weight_decay: 0.00001
  epochs: 20
  device: cpu

predict:
  subset: valid